#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# emacs
export PATH=$PATH:/Applications/Emacs.app/Contents/MacOS/bin

# Julia
export PATH=/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin:$PATH

# R 
export PATH=/Library/Frameworks/R.framework/Versions/Current/Resources/bin:$PATH

# NCL
export NCARG_ROOT=/opt/ncl
export PATH=$NCARG_ROOT/bin:$PATH

# Latexlive (for)
export PATH=/Library/Tex/texbin/:$PATH

# go 
export PATH=~/.gocode/bin:$PATH

# go app engine
export PATH=/opt/go_appengine/:$PATH

# open coarrays
[ -f /opt/OpenCoarrays-1.3.6/opencoarrays-installation/setup.sh ] && source /opt/OpenCoarrays-1.3.6/opencoarrays-installation/setup.sh

if [[ -e /Users/noah ]]; then
    PATH="/Users/noah/perl5/bin${PATH+:}${PATH}"; export PATH;
    PERL5LIB="/Users/noah/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
    PERL_LOCAL_LIB_ROOT="/Users/noah/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
    PERL_MB_OPT="--install_base \"/Users/noah/perl5\""; export PERL_MB_OPT;
    PERL_MM_OPT="INSTALL_BASE=/Users/noah/perl5"; export PERL_MM_OPT;
fi

# vapor
export PATH=/Applications/VAPOR/VAPOR.app/Contents/MacOS:$PATH

# python
export PATH=$HOME/usr/bin:/Users/noah/anaconda/bin:$PATH

# GNL
export PYTHONPATH=$HOME/Dropbox/gnl:$PYTHONPATH
